
import React from 'react';
import { Book, University, BookCondition } from './types';

// Comprehensive list of Egyptian Universities
export const EGYPTIAN_UNIVERSITIES = [
  'Ain Shams University',
  'Al-Azhar University',
  'Alexandria University',
  'Assiut University',
  'Cairo University',
  'Mansoura University',
  'Zagazig University',
  'Helwan University',
  'Suez Canal University',
  'Tanta University',
  'Beni-Suef University',
  'Minia University',
  'South Valley University',
  'Kafrelsheikh University',
  'Suez University',
  'Damietta University',
  'Aswan University',
  'Damanhour University',
  'Fayoum University',
  'Menoufia University',
  'Port Said University',
  'Sohag University',
  'Luxor University',
  'New Valley University',
  'Sinai University',
  '6th October University',
  'Modern Sciences and Arts University (MSA)',
  'Misr University for Science and Technology',
  'Nile University',
  'German University in Cairo (GUC)',
  'British University in Egypt (BUE)',
  'American University in Cairo (AUC)',
  'Ahram Canadian University',
  'Arab Academy for Science, Technology & Maritime Transport',
  'Cairo University - Faculty of Engineering',
  'Future University in Egypt',
  'Heliopolis University',
  'Newgiza University',
  'Pharos University in Alexandria',
  'Suez Canal University',
  'Université Française d\'Égypte',
  'Al-Alsun University',
  'Al-Ahram Canadian University',
  'Al-Nahda University',
  'Al-Shorouk Academy',
  'Arab Open University',
  'Canadian International College',
  'Delta University',
  'Egyptian E-Learning University',
  'Egyptian Russian University',
  'Higher Institute of Applied Arts',
  'Higher Institute of Engineering',
  'Higher Institute of Technology',
  'Horus University',
  'International Academy for Engineering and Media Science',
  'Mansoura University',
  'Middlesex University Egypt',
  'Modern University for Technology and Information',
  'MTI University',
  'National University',
  'New Cairo Academy',
  'October 6 University',
  'Sadat Academy for Management Sciences',
  'Sinai University',
  'Thebes Academy',
  'Université Senghor',
];

export const UNIVERSITIES: University[] = ['All Universities', 'BUE', 'AUC', 'GUC'];

export const CONDITIONS: BookCondition[] = ['New', 'Like New', 'Good', 'Fair'];

export const PIRACY_KEYWORDS = [
  'soft copy',
  'scan',
  'ebook',
  'link',
  'drive',
  'pdf only',
  'cracked'
];

export const MOCK_BOOKS: Book[] = [
  {
    id: '1',
    title: 'Modern Operating Systems',
    author_doctor: 'Andrew S. Tanenbaum',
    university: 'BUE',
    subject: 'Computer Science',
    grade_year: 'Year 2',
    condition: 'Good',
    edition: '4th Ed',
    price: 450,
    description: 'Great condition, some highlights but very readable.',
    photos: 'https://picsum.photos/seed/os/400/600',
    pdf_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    status: 'approved',
    seller_id: 's1',
    seller_name: 'Ahmed Ali',
    seller_phone: '01012345678',
    quantity: 1,
    created_at: new Date().toISOString()
  },
  {
    id: '2',
    title: 'Principles of Economics',
    author_doctor: 'N. Gregory Mankiw',
    university: 'AUC',
    subject: 'Economics',
    grade_year: 'Year 1',
    condition: 'Like New',
    edition: '9th Ed',
    price: 800,
    description: 'Hardly used. Still has the original smell!',
    photos: 'https://picsum.photos/seed/econ/400/600',
    status: 'approved',
    seller_id: 's2',
    seller_name: 'Sara Ibrahim',
    seller_phone: '01198765432',
    quantity: 2,
    created_at: new Date().toISOString()
  },
  {
    id: '3',
    title: 'Advanced Engineering Math',
    author_doctor: 'Erwin Kreyszig',
    university: 'GUC',
    subject: 'Engineering',
    grade_year: 'Year 3',
    condition: 'Good',
    edition: '10th Ed',
    price: 600,
    photos: 'https://picsum.photos/seed/math/400/600',
    status: 'pending',
    seller_id: 's3',
    seller_name: 'Mona Hassan',
    seller_phone: '01234567890',
    quantity: 1,
    created_at: new Date().toISOString()
  }
];
